/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuestionAnswerPair = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const CheatSheetInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Vec(QuestionAnswerPair),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CheatSheet = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Vec(QuestionAnswerPair),
  'createdAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSheet' : IDL.Func([CheatSheetInput], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteSheet' : IDL.Func([IDL.Text], [], []),
  'getAllSheets' : IDL.Func([], [IDL.Vec(CheatSheet)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSheetsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CheatSheet)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuestionAnswerPair = IDL.Record({
    'question' : IDL.Text,
    'answer' : IDL.Text,
  });
  const CheatSheetInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Vec(QuestionAnswerPair),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CheatSheet = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Vec(QuestionAnswerPair),
    'createdAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSheet' : IDL.Func([CheatSheetInput], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteSheet' : IDL.Func([IDL.Text], [], []),
    'getAllSheets' : IDL.Func([], [IDL.Vec(CheatSheet)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSheetsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CheatSheet)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };